name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run bash-environment-manager      
      run: |
        sudo bash .repo/mock_vagrant.sh
        sudo bash .repo/download_bash_environment_manager.sh
        sudo -H -u vagrant bash -c 'cd /vagrant; sudo make conda"
